export * as RequestCapture from "./request-capture"

// offline-fork: keeps the last HTTP request sent to an LLM provider per session so the
// TUI /curl command can dump it as a reusable curl script for reproducing backend errors.

import os from "os"
import path from "path"
import fs from "fs/promises"
import { Effect, Schema } from "effect"
import { HttpRouter, HttpServerResponse } from "effect/unstable/http"

export interface Captured {
  sessionID: string
  timestamp: number
  url: string
  method: string
  headers: Record<string, string>
  body: string
}

const LIMIT = 100
const requests = new Map<string, Captured>()

export function capture(input: unknown, init?: RequestInit) {
  const request = input instanceof Request ? input : undefined
  const headers = Object.fromEntries(new Headers(init?.headers ?? request?.headers))
  const sessionID = headers["x-opencode-session-id"]
  if (!sessionID) return
  requests.delete(sessionID)
  requests.set(sessionID, {
    sessionID,
    timestamp: Date.now(),
    url: request?.url ?? String(input),
    method: init?.method ?? request?.method ?? "GET",
    headers,
    body: typeof init?.body === "string" ? init.body : "",
  })
  for (const key of requests.keys()) {
    if (requests.size <= LIMIT) break
    requests.delete(key)
  }
}

export function get(sessionID: string) {
  return requests.get(sessionID)
}

const quote = (value: string) => `'${value.replaceAll("'", `'\\''`)}'`

// The body is read from the file passed as $1 so the payload can be edited and replayed.
export function curl(request: Captured) {
  return [
    `curl -X ${request.method} ${quote(request.url)}`,
    ...Object.entries(request.headers)
      .filter(([key]) => key !== "content-length")
      .map(([key, value]) => `-H ${quote(`${key}: ${value}`)}`),
    ...(request.body ? [`-d @"$1"`] : []),
  ].join(" \\\n  ")
}

export function script(request: Captured) {
  return `#!/bin/sh
# Usage: $0 <json-file>
# Generated by opencode /curl command

if [ -z "$1" ]; then
  echo "Usage: $0 <json-file>" >&2
  exit 1
fi

if [ ! -f "$1" ]; then
  echo "Error: File '$1' not found" >&2
  exit 1
fi

${curl(request)}
`
}

function pretty(body: string) {
  try {
    return JSON.stringify(JSON.parse(body), null, 2)
  } catch {
    return body
  }
}

export const DumpInput = Schema.Struct({
  sessionID: Schema.String,
  slug: Schema.optional(Schema.String),
  parentSlug: Schema.optional(Schema.String),
})

export async function dump(input: typeof DumpInput.Type) {
  const request = requests.get(input.sessionID)
  if (!request) return { success: false as const, error: "No HTTP request has been captured for this session" }
  const dir = path.join(os.homedir(), ".opencode", "debug")
  await fs.mkdir(dir, { recursive: true })
  const scriptPath = path.join(dir, "llm-request.sh")
  const jsonPath = path.join(
    dir,
    [input.slug ?? input.sessionID, ...(input.parentSlug ? [`from-${input.parentSlug}`] : []), request.timestamp].join(
      "-",
    ) + ".json",
  )
  await fs.writeFile(scriptPath, script(request), { mode: 0o755 })
  await fs.writeFile(jsonPath, pretty(request.body))
  return { success: true as const, scriptPath, jsonPath }
}

// Raw route (outside the public HttpApi/SDK surface) used by the TUI /curl command.
export const route = HttpRouter.use((router) =>
  router.add("POST", "/offline/dump-request", (request) =>
    Effect.gen(function* () {
      const input = yield* request.json.pipe(Effect.flatMap(Schema.decodeUnknownEffect(DumpInput)), Effect.option)
      if (input._tag === "None")
        return HttpServerResponse.jsonUnsafe({ success: false, error: "Invalid request" }, { status: 400 })
      return HttpServerResponse.jsonUnsafe(yield* Effect.promise(() => dump(input.value)))
    }),
  ),
)
